---
patch_dir: "/home/adminuser/non_critical_patching"
pre_patch_file: "pre_patching_list.txt"
post_patch_file: "post_patching_report.txt"
recipient_email: "shravans1302@gmail.com"
email_username: "life14813@gmail.com"
email_password: "hdec kxjf mhcl rbfr"
